# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:      
  testrailswitch:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/master
      - name: echo1
        shell: bash
        run: |
          date
          pwd
          ls -la
          cat README.md
          echo "branch switch"
          env

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: refs/heads/master

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 13

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check test

      #- name: Run tests
      #  run: ./gradlew check test
#        env:
#          GITHUB_TOKEN: ${{ secrets.EVEREE_BOT_GITHUB_TOKEN }}
#          SPRING_PROFILES_ACTIVE: test # Integration tests make calls to https://api-test.everee.com

      - name: Publish test results
        uses: enricomi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/test/TEST-*.xml
          check_name: test_results
          comment_mode: off
          
